### ISSUE TITLE
When enabled, HTML auto complete is not active

### ISSUE THREAD

**Issue by ZBishopM** [samuel-weinhardt/vscode-jsp-lang#1]
I dont' know if it's possible to have the highlight of JSP, but also the auto complete of HTML.
Steps to reproduce:
- Installed the extension
- Trying to write the title of a mark in HTML. Ex: h1 
- Press enter to get the autocompleted mark
- autocomplete not working

**Comment by samuel-weinhardt** [comment]
@ZBishopM To get proper completion support the extension would need a [language server](https://code.visualstudio.com/api/language-extensions/embedded-languages) which I'm not planning to spend time on for now, but if you're just looking for emmet abbreviations I added these instructions to the readme:

To enable [emmet abbreviations](https://code.visualstudio.com/docs/editor/emmet#_emmet-abbreviations-in-other-file-types) for JSP files (for example, to expand `h1` to `<h1></h1>`), add the following configuration to your settings:

```json
"emmet.includeLanguages": {
    "jsp": "html"
}
```

**Comment by ZBishopM** [comment]
Thanks for your time and your quick response, that worked for me.
