### ISSUE TITLE
this extension doesn't highlight the html part of the jsp correctly.

### ISSUE THREAD

**Issue by lkyu-ly** [samuel-weinhardt/vscode-jsp-lang#3]
I'm totally new to java. For some reason this extension doesn't highlight the html part of the jsp correctly.

As shown in the figure below:

![image](https://github.com/user-attachments/assets/4e0a3a45-3444-4234-ae47-c5407fbeec94)
![image](https://github.com/user-attachments/assets/25b8d4ad-116c-4b0a-96bb-200c0254110c)

The first few lines get syntax highlighting, but the later parts remain as they are. I'm sure that I selected “Jakarta Server Pages” in the “Language Mode” of the file, and also add 
```json
"emmet.includeLanguages": {
    "jsp": "html"
}
```
to my `settings.json`.

Could you show me how may I get correctly as shown in Readme? Thanks!

**Comment by samuel-weinhardt** [comment]
Thanks for the report @lkyu-ly, this issue is caused by some issues in the syntax highlighting grammar. I just published an update that should resolve the issue - please let me know if it is resolved once your extension updates to version 0.1.9.

**Comment by lkyu-ly** [comment]
> Thanks for the report @lkyu-ly, this issue is caused by some issues in the syntax highlighting grammar. I just published an update that should resolve the issue - please let me know if it is resolved once your extension updates to version 0.1.9.

Thanks! This worked for me and solved my problem perfectly!

![image](https://github.com/user-attachments/assets/e8e9f8fc-a9ae-49ee-8a2f-862ee63a619c)_It looks pretty well._

Thank you for all your assistance and quick response to me.
